### ISSUE TITLE
ws.readExecutor is not a function

### ISSUE THREAD

**Issue by LucasMontero** [bennymeg/nx-electron#263]
**Describe the bug**

After updating from version 16.0.0 to 16.1.0  the error `ws.readExecutor is not a function` appears when you run `nx run application:serve` being serve:

```
    "serve": {
      "executor": "nx-electron:execute",
      "options": {
        "buildTarget": "application:build"
      }
    },
```

**To Reproduce**
1. Build main and renderer processes
2. Serve main process.

**Expected behavior**

Application should start with normality.

**Screenshots**

![image](https://github.com/bennymeg/nx-electron/assets/7733283/d8b77fd3-85c9-469d-ac72-add9046fcef9)

**Desktop (please complete the following information):**

 - OS: Fedora
 - Nx Electron Version: 16.1.0

**Additional context**

The error doesn't appear on a packaged application.

**Comment by LucasMontero** [comment]
After further testing, I couldn't relate this error to `nx-electron`. I proceed to close the issue.
