### ISSUE TITLE
NX 17 support

### ISSUE THREAD

**Issue by andirsun** [bennymeg/nx-electron#260]
NX 17 just launched.

V16 of nx-electron is supported ?

**Comment by lswnsn** [comment]
in my environment,  when upgrade nx to 17.1.1,  use nx invoke nx-electron:build, there is bellow error:

>  NX   Cannot find module '@nx/workspace/src/utilities/buildable-libs-utils'

   Require stack:
   - /home/shlv/workspace/upgrade/webem/node_modules/nx-electron/src/executors/build/executor.js
   - /home/shlv/workspace/upgrade/webem/node_modules/nx/src/config/schema-utils.js
   - /home/shlv/workspace/upgrade/webem/node_modules/nx/src/command-line/run/executor-utils.js
   - /home/shlv/workspace/upgrade/webem/node_modules/nx/src/command-line/run/run.js
   - /home/shlv/workspace/upgrade/webem/node_modules/nx/bin/run-executor.js
   Pass --verbose to see the stacktrace.

so need nx-electron to upgrade to 17 version to support nx-electron build in nx 17 version

**Comment by bennymeg** [comment]
Not yet.

**Comment by lswnsn** [comment]
@bennymeg so when nx-electron v17 version can released? thanks.

**Comment by the0rem** [comment]
@bennymeg I can see this has been marked as completed, but I can't see any PR, commit, or open issue that tracks the NX 17 upgrade?

**Comment by bennymeg** [comment]
@lswnsn Released in NPM.
@the0rem There is v17 branch.

**Comment by lswnsn** [comment]
@bennymeg  thanks
